/*
 * Offentlig Akvakulturregister
 *
 * API for det nye offentlige Akvakulturregisteret
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: akva-hjelp@fiskeridir.no
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Address : Adresse.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Address {
    /// Unik identifikator for addressen.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i64>,
    /// Addressetypen.
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    /// Verdi.
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
    /// Postnummeret som addressen hører til.
    #[serde(rename = "zipCode", skip_serializing_if = "Option::is_none")]
    pub zip_code: Option<String>,
    /// Poststedet som addressen hører til.
    #[serde(rename = "zipName", skip_serializing_if = "Option::is_none")]
    pub zip_name: Option<String>,
    /// Fylkesnummeret som addressen hører til.
    #[serde(rename = "countyCode", skip_serializing_if = "Option::is_none")]
    pub county_code: Option<String>,
    /// Fylkesnavnet hvor addressen er.
    #[serde(rename = "countyName", skip_serializing_if = "Option::is_none")]
    pub county_name: Option<String>,
    /// Landskoden hvor addressen er.
    #[serde(rename = "countryCode", skip_serializing_if = "Option::is_none")]
    pub country_code: Option<String>,
    /// Navnet på landet addressen ligger i.
    #[serde(rename = "countryName", skip_serializing_if = "Option::is_none")]
    pub country_name: Option<String>,
    /// Offisiell kildetype for addressen.
    #[serde(rename = "officialSourceType", skip_serializing_if = "Option::is_none")]
    pub official_source_type: Option<String>,
}

impl Address {
    /// Adresse.
    pub fn new() -> Address {
        Address {
            id: None,
            r#type: None,
            value: None,
            zip_code: None,
            zip_name: None,
            county_code: None,
            county_name: None,
            country_code: None,
            country_name: None,
            official_source_type: None,
        }
    }
}

