/*
 * Offentlig Akvakulturregister
 *
 * API for det nye offentlige Akvakulturregisteret
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: akva-hjelp@fiskeridir.no
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AreaListItem : Geografisk informasjon om et spesifikt område.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AreaListItem {
    /// Unik identifikator.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i64>,
    /// Områdetypen
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    /// Standardkode
    #[serde(rename = "defaultCode", skip_serializing_if = "Option::is_none")]
    pub default_code: Option<String>,
    /// Standardnavn
    #[serde(rename = "defaultName", skip_serializing_if = "Option::is_none")]
    pub default_name: Option<String>,
    /// Forkortelse av navnet på området lokaliteten ligger på.
    #[serde(rename = "shortName", skip_serializing_if = "Option::is_none")]
    pub short_name: Option<String>,
    /// Navnet på området lokaliteten ligger på.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Unik versjonsidentifikator
    #[serde(rename = "versionId", skip_serializing_if = "Option::is_none")]
    pub version_id: Option<i64>,
    /// Tidsstempel for når lokaliteten ble godkjent til å benytte seg av området.
    #[serde(rename = "validFrom", skip_serializing_if = "Option::is_none")]
    pub valid_from: Option<String>,
    /// Sluttid for når lokaliteten er godkjent til å benytte seg av området
    #[serde(rename = "validUntil", skip_serializing_if = "Option::is_none")]
    pub valid_until: Option<String>,
    /// Unik identifikator for neste versjon.
    #[serde(rename = "versionNextId", skip_serializing_if = "Option::is_none")]
    pub version_next_id: Option<i64>,
}

impl AreaListItem {
    /// Geografisk informasjon om et spesifikt område.
    pub fn new() -> AreaListItem {
        AreaListItem {
            id: None,
            r#type: None,
            default_code: None,
            default_name: None,
            short_name: None,
            name: None,
            version_id: None,
            valid_from: None,
            valid_until: None,
            version_next_id: None,
        }
    }
}
