/*
 * Offentlig Akvakulturregister
 *
 * API for det nye offentlige Akvakulturregisteret
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: akva-hjelp@fiskeridir.no
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AreaPlacement : Geografisk beskrivelse av området.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AreaPlacement {
    /// Kommunenummeret som området er registrert til.
    #[serde(rename = "municipalityCode", skip_serializing_if = "Option::is_none")]
    pub municipality_code: Option<String>,
    /// Kommunenavnet som området er registrert til.
    #[serde(rename = "municipalityName", skip_serializing_if = "Option::is_none")]
    pub municipality_name: Option<String>,
    /// Fylkesnummeret som området er registrert til.
    #[serde(rename = "countyCode", skip_serializing_if = "Option::is_none")]
    pub county_code: Option<String>,
    /// Fylkesnavnet som området er registrert til.
    #[serde(rename = "countyName", skip_serializing_if = "Option::is_none")]
    pub county_name: Option<String>,
    /// Produksjonsområdet som området er registrert til.
    #[serde(rename = "prodAreaCode", skip_serializing_if = "Option::is_none")]
    pub prod_area_code: Option<String>,
    /// Navnet på produksjonsområdet som området er registrert til.
    #[serde(rename = "prodAreaName", skip_serializing_if = "Option::is_none")]
    pub prod_area_name: Option<String>,
    /// Statusen til produksjonsområdet.
    #[serde(rename = "prodAreaStatus", skip_serializing_if = "Option::is_none")]
    pub prod_area_status: Option<String>,
}

impl AreaPlacement {
    /// Geografisk beskrivelse av området.
    pub fn new() -> AreaPlacement {
        AreaPlacement {
            municipality_code: None,
            municipality_name: None,
            county_code: None,
            county_name: None,
            prod_area_code: None,
            prod_area_name: None,
            prod_area_status: None,
        }
    }
}
