/*
 * Offentlig Akvakulturregister
 *
 * API for det nye offentlige Akvakulturregisteret
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: akva-hjelp@fiskeridir.no
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BorderPoint : Grensepunkt beskrevet i bredde- og lengdegrad i desimalgrader.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BorderPoint {
    /// Unik identifikator
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i64>,
    /// En indeks som representerer en unik identifikator for hvert grensepunkt.
    #[serde(rename = "index", skip_serializing_if = "Option::is_none")]
    pub index: Option<i32>,
    /// Breddegrad
    #[serde(rename = "latitude", skip_serializing_if = "Option::is_none")]
    pub latitude: Option<f64>,
    /// Lengdegrad
    #[serde(rename = "longitude", skip_serializing_if = "Option::is_none")]
    pub longitude: Option<f64>,
}

impl BorderPoint {
    /// Grensepunkt beskrevet i bredde- og lengdegrad i desimalgrader.
    pub fn new() -> BorderPoint {
        BorderPoint {
            id: None,
            index: None,
            latitude: None,
            longitude: None,
        }
    }
}
