/*
 * Offentlig Akvakulturregister
 *
 * API for det nye offentlige Akvakulturregisteret
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: akva-hjelp@fiskeridir.no
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BorderType : Grensetype.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BorderType {
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
}

impl BorderType {
    /// Grensetype.
    pub fn new() -> BorderType {
        BorderType { value: None }
    }
}
