/*
 * Offentlig Akvakulturregister
 *
 * API for det nye offentlige Akvakulturregisteret
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: akva-hjelp@fiskeridir.no
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CapacityInfo : Informasjon om kapasitet.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CapacityInfo {
    /// Akkumulert kapasitet.
    #[serde(rename = "accumulated", skip_serializing_if = "Option::is_none")]
    pub accumulated: Option<f64>,
    /// Nåværende kapasitet.
    #[serde(rename = "current", skip_serializing_if = "Option::is_none")]
    pub current: Option<f64>,
    /// Enhet, f.eks. Tonn.
    #[serde(rename = "unit", skip_serializing_if = "Option::is_none")]
    pub unit: Option<String>,
    /// Kapasistetstypen
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
}

impl CapacityInfo {
    /// Informasjon om kapasitet.
    pub fn new() -> CapacityInfo {
        CapacityInfo {
            accumulated: None,
            current: None,
            unit: None,
            r#type: None,
        }
    }
}
