/*
 * Offentlig Akvakulturregister
 *
 * API for det nye offentlige Akvakulturregisteret
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: akva-hjelp@fiskeridir.no
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FishCode : Fiskekode.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FishCode {
    /// Artskoden til gitt fisk, f.eks \"071101\".
    #[serde(rename = "code", skip_serializing_if = "Option::is_none")]
    pub code: Option<String>,
    /// Det latinske navnet på fisken, f.eks. \"Salmo salar\".
    #[serde(rename = "latinName", skip_serializing_if = "Option::is_none")]
    pub latin_name: Option<String>,
    /// Fiskens navn på bokmål, f.eks. \"Laks\".
    #[serde(rename = "nbNoName", skip_serializing_if = "Option::is_none")]
    pub nb_no_name: Option<String>,
    /// Fiskens navn på nynorsk.
    #[serde(rename = "nnNoName", skip_serializing_if = "Option::is_none")]
    pub nn_no_name: Option<String>,
    /// Fiskens navn på engelsk, f.eks. \"Salmon\".
    #[serde(rename = "enGbName", skip_serializing_if = "Option::is_none")]
    pub en_gb_name: Option<String>,
}

impl FishCode {
    /// Fiskekode.
    pub fn new() -> FishCode {
        FishCode {
            code: None,
            latin_name: None,
            nb_no_name: None,
            nn_no_name: None,
            en_gb_name: None,
        }
    }
}
