/*
 * Offentlig Akvakulturregister
 *
 * API for det nye offentlige Akvakulturregisteret
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: akva-hjelp@fiskeridir.no
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// IntentionType : Informasjon om formålstypen.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IntentionType {
    /// Unik identifikator for formålstypen.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    /// Verdi.
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
    /// Lokalisert verdi.
    #[serde(rename = "localizedValue", skip_serializing_if = "Option::is_none")]
    pub localized_value: Option<String>,
    /// Navnet på reguleringen for formålet.
    #[serde(rename = "regulationName", skip_serializing_if = "Option::is_none")]
    pub regulation_name: Option<String>,
}

impl IntentionType {
    /// Informasjon om formålstypen.
    pub fn new() -> IntentionType {
        IntentionType {
            id: None,
            value: None,
            localized_value: None,
            regulation_name: None,
        }
    }
}

