/*
 * Offentlig Akvakulturregister
 *
 * API for det nye offentlige Akvakulturregisteret
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: akva-hjelp@fiskeridir.no
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// LatestLicenseSiteConnectionOverview : Oversikt over siste tilkoblingstillatelse til lokalitet.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LatestLicenseSiteConnectionOverview {
    /// Tillatelsesnummer
    #[serde(rename = "licenseNr", skip_serializing_if = "Option::is_none")]
    pub license_nr: Option<String>,
    /// Lokalitetsnummer
    #[serde(rename = "siteNr", skip_serializing_if = "Option::is_none")]
    pub site_nr: Option<String>,
    /// Tidsstempel for når den siste tilkoblingstillatelsen er gyldig fra.
    #[serde(rename = "validFrom", skip_serializing_if = "Option::is_none")]
    pub valid_from: Option<String>,
    /// Tidsstempel for når den siste tilkoblingstillatelsen er gyldig til.
    #[serde(rename = "validUntil", skip_serializing_if = "Option::is_none")]
    pub valid_until: Option<String>,
    /// Tidsstempel for når den siste tilkoblingstillatelsen er midlertidig gyldig til.
    #[serde(rename = "temporaryUntil", skip_serializing_if = "Option::is_none")]
    pub temporary_until: Option<String>,
    /// Status
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    /// Statusverdi.
    #[serde(rename = "statusValue", skip_serializing_if = "Option::is_none")]
    pub status_value: Option<String>,
}

impl LatestLicenseSiteConnectionOverview {
    /// Oversikt over siste tilkoblingstillatelse til lokalitet.
    pub fn new() -> LatestLicenseSiteConnectionOverview {
        LatestLicenseSiteConnectionOverview {
            license_nr: None,
            site_nr: None,
            valid_from: None,
            valid_until: None,
            temporary_until: None,
            status: None,
            status_value: None,
        }
    }
}

