/*
 * Offentlig Akvakulturregister
 *
 * API for det nye offentlige Akvakulturregisteret
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: akva-hjelp@fiskeridir.no
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// LatestLicenseSiteConnectionDetail : Detaljert informasjon om lokalitetstilkoblingen som senest ble registrert til gitt lokalitet.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LatestLicenseSiteConnectionDetail {
    /// Nøkkel
    #[serde(rename = "key", skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    /// Unik tillatelsesidentifikator.
    #[serde(rename = "licenseId", skip_serializing_if = "Option::is_none")]
    pub license_id: Option<i64>,
    /// Tillatelsesnummer
    #[serde(rename = "licenseNr", skip_serializing_if = "Option::is_none")]
    pub license_nr: Option<String>,
    /// Unik lokalitets-identifikator.
    #[serde(rename = "siteId", skip_serializing_if = "Option::is_none")]
    pub site_id: Option<i64>,
    /// Lokalitetsnummer
    #[serde(rename = "siteNr", skip_serializing_if = "Option::is_none")]
    pub site_nr: Option<String>,
    /// Lokalitetsnavn
    #[serde(rename = "siteName", skip_serializing_if = "Option::is_none")]
    pub site_name: Option<String>,
    /// Tidsstempel for når lokalitetstilkoblingen ble gyldig.
    #[serde(rename = "validFrom", skip_serializing_if = "Option::is_none")]
    pub valid_from: Option<String>,
    /// Tidsstempel for når lokalitetstilkoblingen er gyldig til.
    #[serde(rename = "validUntil", skip_serializing_if = "Option::is_none")]
    pub valid_until: Option<String>,
    /// Tidsstempel for når lokalitetstilkoblingen er midlertidig gyldig til.
    #[serde(rename = "temporaryUntil", skip_serializing_if = "Option::is_none")]
    pub temporary_until: Option<String>,
    /// Tidsstempel for nå lokalitetstilkoblingen ble registrert til gitt lokalitet.
    #[serde(rename = "registeredTime", skip_serializing_if = "Option::is_none")]
    pub registered_time: Option<String>,
    /// Om lokalitetstilkoblingen til tillatelsen er aktiv.
    #[serde(rename = "active", skip_serializing_if = "Option::is_none")]
    pub active: Option<bool>,
    /// Status på lokalitetstilkoblingene til tillatelsen.
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    /// Statusverdi
    #[serde(rename = "statusValue", skip_serializing_if = "Option::is_none")]
    pub status_value: Option<String>,
}

impl LatestLicenseSiteConnectionDetail {
    /// Detaljert informasjon om lokalitetstilkoblingen som senest ble registrert til gitt lokalitet.
    pub fn new() -> LatestLicenseSiteConnectionDetail {
        LatestLicenseSiteConnectionDetail {
            key: None,
            license_id: None,
            license_nr: None,
            site_id: None,
            site_nr: None,
            site_name: None,
            valid_from: None,
            valid_until: None,
            temporary_until: None,
            registered_time: None,
            active: None,
            status: None,
            status_value: None,
        }
    }
}

