/*
 * Offentlig Akvakulturregister
 *
 * API for det nye offentlige Akvakulturregisteret
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: akva-hjelp@fiskeridir.no
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// LicenseDetail : Detaljert informasjon om tillatelser gitt til en innehaver.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LicenseDetail {
    /// Unik tillatelses-identifikator
    #[serde(rename = "licenseId", skip_serializing_if = "Option::is_none")]
    pub license_id: Option<i64>,
    /// Versjons-ID
    #[serde(rename = "versionId", skip_serializing_if = "Option::is_none")]
    pub version_id: Option<i64>,
    /// Tillatelsesnummer
    #[serde(rename = "licenseNr", skip_serializing_if = "Option::is_none")]
    pub license_nr: Option<String>,
    /// Tillatelsesnummer som ble brukt når tillatelsen ble registrert.
    #[serde(rename = "originalLicenseNr", skip_serializing_if = "Option::is_none")]
    pub original_license_nr: Option<String>,
    /// Arvet tillatelsesnummer
    #[serde(rename = "legacyLicenseNr", skip_serializing_if = "Option::is_none")]
    pub legacy_license_nr: Option<String>,
    #[serde(rename = "portfolioType", skip_serializing_if = "Option::is_none")]
    pub portfolio_type: Option<Box<models::LicensePortfolioType>>,
    /// Identifikatoren for hovedtillatelsen i tillatelsesporteføljen.
    #[serde(
        rename = "portfolioMasterLicenseId",
        skip_serializing_if = "Option::is_none"
    )]
    pub portfolio_master_license_id: Option<i64>,
    /// Juridisk-enhetsnummer-identifikator.
    #[serde(rename = "legalEntityNrId", skip_serializing_if = "Option::is_none")]
    pub legal_entity_nr_id: Option<String>,
    /// Åpent juridisk enhetsnummer.
    #[serde(rename = "openLegalEntityNr", skip_serializing_if = "Option::is_none")]
    pub open_legal_entity_nr: Option<String>,
    /// Juridisk enhetsnavn.
    #[serde(rename = "legalEntityName", skip_serializing_if = "Option::is_none")]
    pub legal_entity_name: Option<String>,
    /// Informasjon om produksjonsregimet til tillatelsen.
    #[serde(rename = "productionRegime", skip_serializing_if = "Option::is_none")]
    pub production_regime: Option<String>,
    /// Informasjon om produksjonsmodellen til tillatelsen.
    #[serde(rename = "productionModel", skip_serializing_if = "Option::is_none")]
    pub production_model: Option<String>,
    #[serde(rename = "capacity", skip_serializing_if = "Option::is_none")]
    pub capacity: Option<Box<models::CapacityInfo>>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<Box<models::LicenseTypeDetail>>,
    #[serde(rename = "species", skip_serializing_if = "Option::is_none")]
    pub species: Option<Box<models::SpeciesDetail>>,
    #[serde(rename = "connections", skip_serializing_if = "Option::is_none")]
    pub connections: Option<Vec<models::LatestLicenseSiteConnectionDetail>>,
    #[serde(rename = "placement", skip_serializing_if = "Option::is_none")]
    pub placement: Option<Box<models::AreaPlacement>>,
    #[serde(rename = "grantInformation", skip_serializing_if = "Option::is_none")]
    pub grant_information: Option<Box<models::GrantInfo>>,
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<Box<models::VersionDetail>>,
}

impl LicenseDetail {
    /// Detaljert informasjon om tillatelser gitt til en innehaver.
    pub fn new() -> LicenseDetail {
        LicenseDetail {
            license_id: None,
            version_id: None,
            license_nr: None,
            original_license_nr: None,
            legacy_license_nr: None,
            portfolio_type: None,
            portfolio_master_license_id: None,
            legal_entity_nr_id: None,
            open_legal_entity_nr: None,
            legal_entity_name: None,
            production_regime: None,
            production_model: None,
            capacity: None,
            r#type: None,
            species: None,
            connections: None,
            placement: None,
            grant_information: None,
            version: None,
        }
    }
}
