/*
 * Offentlig Akvakulturregister
 *
 * API for det nye offentlige Akvakulturregisteret
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: akva-hjelp@fiskeridir.no
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// LicenseTypeOverview : Oversikt over tillatelsestyper.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LicenseTypeOverview {
    /// Formålet med tillatelsestypen.
    #[serde(rename = "intention", skip_serializing_if = "Option::is_none")]
    pub intention: Option<String>,
    /// Formålsverdi
    #[serde(rename = "intentionValue", skip_serializing_if = "Option::is_none")]
    pub intention_value: Option<String>,
    /// Hva som blir produsert på tillatelsen.
    #[serde(rename = "produces", skip_serializing_if = "Option::is_none")]
    pub produces: Option<String>,
    /// Produksjonsverdi.
    #[serde(rename = "producesValue", skip_serializing_if = "Option::is_none")]
    pub produces_value: Option<String>,
    /// Den nåværende fasen av produksjonsprosessen til tillatelsen.
    #[serde(rename = "productionStage", skip_serializing_if = "Option::is_none")]
    pub production_stage: Option<String>,
    /// Verdien til produksjonsprosess-fasen.
    #[serde(rename = "productionStageValue", skip_serializing_if = "Option::is_none")]
    pub production_stage_value: Option<String>,
    /// Etikett som f.eks. KOMM-MATF.
    #[serde(rename = "tag", skip_serializing_if = "Option::is_none")]
    pub tag: Option<String>,
    /// Informasjon om fordelingen av ressurser på tillatelsen.
    #[serde(rename = "allocationInformation", skip_serializing_if = "Option::is_none")]
    pub allocation_information: Option<String>,
}

impl LicenseTypeOverview {
    /// Oversikt over tillatelsestyper.
    pub fn new() -> LicenseTypeOverview {
        LicenseTypeOverview {
            intention: None,
            intention_value: None,
            produces: None,
            produces_value: None,
            production_stage: None,
            production_stage_value: None,
            tag: None,
            allocation_information: None,
        }
    }
}

