/*
 * Offentlig Akvakulturregister
 *
 * API for det nye offentlige Akvakulturregisteret
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: akva-hjelp@fiskeridir.no
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// LicenseTransfers : Informasjon om overføringer av tillatelser mellom juridiske enheter.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LicenseTransfers {
    /// Ajour-dato for når overføringen av tillatelsen ble gjennomført.
    #[serde(rename = "ajourDate", skip_serializing_if = "Option::is_none")]
    pub ajour_date: Option<String>,
    #[serde(rename = "transfers", skip_serializing_if = "Option::is_none")]
    pub transfers: Option<Vec<models::Transfer>>,
}

impl LicenseTransfers {
    /// Informasjon om overføringer av tillatelser mellom juridiske enheter.
    pub fn new() -> LicenseTransfers {
        LicenseTransfers {
            ajour_date: None,
            transfers: None,
        }
    }
}
