/*
 * Offentlig Akvakulturregister
 *
 * API for det nye offentlige Akvakulturregisteret
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: akva-hjelp@fiskeridir.no
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// LicensePortfolioType : Porteføljetypen til tillatelsen.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LicensePortfolioType {
    /// Verdi
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
    /// Verdi brukt til å spesifisere søknadskriterier ved forespørsel mot API.
    #[serde(rename = "apiSearchValue", skip_serializing_if = "Option::is_none")]
    pub api_search_value: Option<String>,
    /// Navnet på porteføljetypen.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

impl LicensePortfolioType {
    /// Porteføljetypen til tillatelsen.
    pub fn new() -> LicensePortfolioType {
        LicensePortfolioType {
            value: None,
            api_search_value: None,
            name: None,
        }
    }
}

