/*
 * Offentlig Akvakulturregister
 *
 * API for det nye offentlige Akvakulturregisteret
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: akva-hjelp@fiskeridir.no
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Lien : Informasjon om panterett.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Lien {
    /// Journalnummer.
    #[serde(rename = "journalNr", skip_serializing_if = "Option::is_none")]
    pub journal_nr: Option<String>,
    /// Tidsstempel for journaldato for panteretten.
    #[serde(rename = "journalDate", skip_serializing_if = "Option::is_none")]
    pub journal_date: Option<String>,
    /// Mengde som inngår i panteretten.
    #[serde(rename = "amount", skip_serializing_if = "Option::is_none")]
    pub amount: Option<f64>,
    /// Valutaen som gjelder for verdien som er sikret av panteretten.
    #[serde(rename = "currency", skip_serializing_if = "Option::is_none")]
    pub currency: Option<String>,
    #[serde(rename = "registeredOwner", skip_serializing_if = "Option::is_none")]
    pub registered_owner: Option<Box<models::RegisteredLicenseOwner>>,
    #[serde(rename = "lienholder", skip_serializing_if = "Option::is_none")]
    pub lienholder: Option<Box<models::Lienholder>>,
}

impl Lien {
    /// Informasjon om panterett.
    pub fn new() -> Lien {
        Lien {
            journal_nr: None,
            journal_date: None,
            amount: None,
            currency: None,
            registered_owner: None,
            lienholder: None,
        }
    }
}
