/*
 * Offentlig Akvakulturregister
 *
 * API for det nye offentlige Akvakulturregisteret
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: akva-hjelp@fiskeridir.no
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// LienHolders : Informasjon om panterettholdere.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LienHolders {
    /// Ajour-dato for panteretten.
    #[serde(rename = "ajourDate", skip_serializing_if = "Option::is_none")]
    pub ajour_date: Option<String>,
    #[serde(rename = "liens", skip_serializing_if = "Option::is_none")]
    pub liens: Option<Vec<models::Lien>>,
}

impl LienHolders {
    /// Informasjon om panterettholdere.
    pub fn new() -> LienHolders {
        LienHolders {
            ajour_date: None,
            liens: None,
        }
    }
}
