/*
 * Offentlig Akvakulturregister
 *
 * API for det nye offentlige Akvakulturregisteret
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: akva-hjelp@fiskeridir.no
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SiteDecision : Vedtak som gjelder for lokaliteten.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SiteDecision {
    /// Unik identifikator
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i64>,
    /// Unik lokalitets-identifikator
    #[serde(rename = "siteId", skip_serializing_if = "Option::is_none")]
    pub site_id: Option<i64>,
    /// Lokalitetsnummer
    #[serde(rename = "siteNr", skip_serializing_if = "Option::is_none")]
    pub site_nr: Option<i32>,
    /// Tidsstempel for når vedtaket ble satt.
    #[serde(rename = "caseGrantedTime", skip_serializing_if = "Option::is_none")]
    pub case_granted_time: Option<String>,
    /// Sakstype
    #[serde(rename = "caseType", skip_serializing_if = "Option::is_none")]
    pub case_type: Option<String>,
    /// Sakstypeverdi
    #[serde(rename = "caseTypeValue", skip_serializing_if = "Option::is_none")]
    pub case_type_value: Option<String>,
    /// Tidsstempel for når vedtaket er gyldig fra.
    #[serde(rename = "validFrom", skip_serializing_if = "Option::is_none")]
    pub valid_from: Option<String>,
    /// Tidsstempel for når vedtaket er gyldig til.
    #[serde(rename = "validUntil", skip_serializing_if = "Option::is_none")]
    pub valid_until: Option<String>,
    /// Vedtakstype
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    /// Vedtakstype-verdi
    #[serde(rename = "typeValue", skip_serializing_if = "Option::is_none")]
    pub type_value: Option<String>,
    /// Tidsstempel for når vedtaket ble registrert.
    #[serde(rename = "registeredTime", skip_serializing_if = "Option::is_none")]
    pub registered_time: Option<String>,
    /// Status på vedtaket.
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    /// Lokalitets-versjons-identifikator.
    #[serde(rename = "siteVersionId", skip_serializing_if = "Option::is_none")]
    pub site_version_id: Option<i64>,
    /// Statusverdi
    #[serde(rename = "statusValue", skip_serializing_if = "Option::is_none")]
    pub status_value: Option<String>,
}

impl SiteDecision {
    /// Vedtak som gjelder for lokaliteten.
    pub fn new() -> SiteDecision {
        SiteDecision {
            id: None,
            site_id: None,
            site_nr: None,
            case_granted_time: None,
            case_type: None,
            case_type_value: None,
            valid_from: None,
            valid_until: None,
            r#type: None,
            type_value: None,
            registered_time: None,
            status: None,
            site_version_id: None,
            status_value: None,
        }
    }
}

