/*
 * Offentlig Akvakulturregister
 *
 * API for det nye offentlige Akvakulturregisteret
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: akva-hjelp@fiskeridir.no
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SiteConnectionForLicense : Informasjon om tillatelsens lokalitetstilknytninger.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SiteConnectionForLicense {
    #[serde(rename = "connectionDetail", skip_serializing_if = "Option::is_none")]
    pub connection_detail: Option<Box<models::LatestLicenseSiteConnectionDetail>>,
    /// Navn
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Kapasistet
    #[serde(rename = "capacity", skip_serializing_if = "Option::is_none")]
    pub capacity: Option<f64>,
    /// Midlertidig kapasitet.
    #[serde(rename = "tempCapacity", skip_serializing_if = "Option::is_none")]
    pub temp_capacity: Option<f64>,
    /// Kapasitetens enhetstype f.eks. Tonn.
    #[serde(rename = "capacityUnitType", skip_serializing_if = "Option::is_none")]
    pub capacity_unit_type: Option<String>,
    #[serde(rename = "placement", skip_serializing_if = "Option::is_none")]
    pub placement: Option<Box<models::AreaPlacement>>,
}

impl SiteConnectionForLicense {
    /// Informasjon om tillatelsens lokalitetstilknytninger.
    pub fn new() -> SiteConnectionForLicense {
        SiteConnectionForLicense {
            connection_detail: None,
            name: None,
            capacity: None,
            temp_capacity: None,
            capacity_unit_type: None,
            placement: None,
        }
    }
}

