/*
 * Offentlig Akvakulturregister
 *
 * API for det nye offentlige Akvakulturregisteret
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: akva-hjelp@fiskeridir.no
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SiteBorder : Grensen til en gitt lokalitet.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SiteBorder {
    /// Unik identifikator
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i64>,
    /// Unik lokalitetsversjons-identifikator
    #[serde(rename = "siteVersionId", skip_serializing_if = "Option::is_none")]
    pub site_version_id: Option<i64>,
    /// Lokalitetsnummer
    #[serde(rename = "siteNr", skip_serializing_if = "Option::is_none")]
    pub site_nr: Option<i32>,
    /// Navnet på lokaliteten.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<Box<models::BorderType>>,
    /// Liste over grensepunkter for en gitt lokalitet.
    #[serde(rename = "points", skip_serializing_if = "Option::is_none")]
    pub points: Option<Vec<models::BorderPoint>>,
    /// Størrelsen på lokaliteten målt i kvadratmeter.
    #[serde(rename = "areaM2", skip_serializing_if = "Option::is_none")]
    pub area_m2: Option<f64>,
}

impl SiteBorder {
    /// Grensen til en gitt lokalitet.
    pub fn new() -> SiteBorder {
        SiteBorder {
            id: None,
            site_version_id: None,
            site_nr: None,
            name: None,
            r#type: None,
            points: None,
            area_m2: None,
        }
    }
}

