/*
 * Offentlig Akvakulturregister
 *
 * API for det nye offentlige Akvakulturregisteret
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: akva-hjelp@fiskeridir.no
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SiteForLegalEntity : Lokalitet som blir benyttet av gitt juridisk enhet.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SiteForLegalEntity {
    /// Lokalitetsnummer
    #[serde(rename = "siteNr", skip_serializing_if = "Option::is_none")]
    pub site_nr: Option<String>,
    /// Navnet på lokaliteten.
    #[serde(rename = "siteName", skip_serializing_if = "Option::is_none")]
    pub site_name: Option<String>,
    /// Tillatt kapasitet for den gitte lokaliteten.
    #[serde(rename = "siteCapacity", skip_serializing_if = "Option::is_none")]
    pub site_capacity: Option<f64>,
    /// Den midlertidige kapasiteten til en lokalitet.
    #[serde(rename = "siteTempCapacity", skip_serializing_if = "Option::is_none")]
    pub site_temp_capacity: Option<f64>,
    /// Kapasitetsenheten som blir brukt for å beskrive kapasitetsmengden på lokaliteten. Oppgitt i f.eks. Tonn.
    #[serde(
        rename = "siteCapacityUnitType",
        skip_serializing_if = "Option::is_none"
    )]
    pub site_capacity_unit_type: Option<String>,
    #[serde(rename = "sitePlacement", skip_serializing_if = "Option::is_none")]
    pub site_placement: Option<Box<models::AreaPlacement>>,
    #[serde(rename = "connections", skip_serializing_if = "Option::is_none")]
    pub connections: Option<Vec<models::LicenseConnectionForSite>>,
    /// Tidsstempel for når lokaliteten begynte å bli benyttet av den juridiske enheten.
    #[serde(rename = "validFrom", skip_serializing_if = "Option::is_none")]
    pub valid_from: Option<String>,
    /// Tidsstempel for når lokaliteten blir benyttet til av den juridiske enheten.
    #[serde(rename = "validUntil", skip_serializing_if = "Option::is_none")]
    pub valid_until: Option<String>,
    /// Tidsstempel for når den gjeldende lokaliteten er midlertidig gyldig til for den juridiske enheten.
    #[serde(rename = "temporaryUntil", skip_serializing_if = "Option::is_none")]
    pub temporary_until: Option<String>,
    /// Status
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    /// Statusverdi
    #[serde(rename = "statusValue", skip_serializing_if = "Option::is_none")]
    pub status_value: Option<String>,
}

impl SiteForLegalEntity {
    /// Lokalitet som blir benyttet av gitt juridisk enhet.
    pub fn new() -> SiteForLegalEntity {
        SiteForLegalEntity {
            site_nr: None,
            site_name: None,
            site_capacity: None,
            site_temp_capacity: None,
            site_capacity_unit_type: None,
            site_placement: None,
            connections: None,
            valid_from: None,
            valid_until: None,
            temporary_until: None,
            status: None,
            status_value: None,
        }
    }
}
