/*
 * Offentlig Akvakulturregister
 *
 * API for det nye offentlige Akvakulturregisteret
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: akva-hjelp@fiskeridir.no
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SpeciesOverview : Oversikt over arter.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SpeciesOverview {
    /// Unik artskomposisjons-identifikator.
    #[serde(rename = "compositionId", skip_serializing_if = "Option::is_none")]
    pub composition_id: Option<i64>,
    /// Liste over fiskekoder.
    #[serde(rename = "fishCodes", skip_serializing_if = "Option::is_none")]
    pub fish_codes: Option<Vec<String>>,
}

impl SpeciesOverview {
    /// Oversikt over arter.
    pub fn new() -> SpeciesOverview {
        SpeciesOverview {
            composition_id: None,
            fish_codes: None,
        }
    }
}

