/*
 * Offentlig Akvakulturregister
 *
 * API for det nye offentlige Akvakulturregisteret
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: akva-hjelp@fiskeridir.no
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Transfer : Overføring av tillatelser mellom juridiske enheter.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Transfer {
    /// Journal nummer for overføringen.
    #[serde(rename = "journalNr", skip_serializing_if = "Option::is_none")]
    pub journal_nr: Option<String>,
    /// Tidsstempel for når journalen ble gjort.
    #[serde(rename = "journalDate", skip_serializing_if = "Option::is_none")]
    pub journal_date: Option<String>,
    /// Unikt identitetsnummer.
    #[serde(rename = "identityNr", skip_serializing_if = "Option::is_none")]
    pub identity_nr: Option<String>,
    /// Offisielt navn.
    #[serde(rename = "officialName", skip_serializing_if = "Option::is_none")]
    pub official_name: Option<String>,
}

impl Transfer {
    /// Overføring av tillatelser mellom juridiske enheter.
    pub fn new() -> Transfer {
        Transfer {
            journal_nr: None,
            journal_date: None,
            identity_nr: None,
            official_name: None,
        }
    }
}
