/*
 * Offentlig Akvakulturregister
 *
 * API for det nye offentlige Akvakulturregisteret
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: akva-hjelp@fiskeridir.no
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// VersionDetail : Detaljert informasjon om en bestemt versjon av forskjellige data.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VersionDetail {
    /// Tidsstempel for når disse versjonsdataene er gyldig fra.
    #[serde(rename = "validFrom", skip_serializing_if = "Option::is_none")]
    pub valid_from: Option<String>,
    /// Tidsstempel for når disse versjonsdataene er gyldig til.
    #[serde(rename = "validUntil", skip_serializing_if = "Option::is_none")]
    pub valid_until: Option<String>,
    /// Tidsstempel for når disse versjonsdataene er midlertidig gyldig til.
    #[serde(rename = "temporaryUntil", skip_serializing_if = "Option::is_none")]
    pub temporary_until: Option<String>,
    /// Tidsstempel for disse versjonsdataene sin registrering.
    #[serde(rename = "registeredTime", skip_serializing_if = "Option::is_none")]
    pub registered_time: Option<String>,
    /// Årsakstypen til versjonsdataene.
    #[serde(rename = "versionCauseType", skip_serializing_if = "Option::is_none")]
    pub version_cause_type: Option<String>,
    /// Årsakstypeverdien
    #[serde(rename = "versionCauseTypeValue", skip_serializing_if = "Option::is_none")]
    pub version_cause_type_value: Option<String>,
    /// Status på versjonen av lokalitetsdataene.
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    /// Statusverdi
    #[serde(rename = "statusValue", skip_serializing_if = "Option::is_none")]
    pub status_value: Option<String>,
    /// Versjonsbar status
    #[serde(rename = "versionableStatus", skip_serializing_if = "Option::is_none")]
    pub versionable_status: Option<String>,
    /// Versjonsbar statusverdi
    #[serde(rename = "versionableStatusValue", skip_serializing_if = "Option::is_none")]
    pub versionable_status_value: Option<String>,
}

impl VersionDetail {
    /// Detaljert informasjon om en bestemt versjon av forskjellige data.
    pub fn new() -> VersionDetail {
        VersionDetail {
            valid_from: None,
            valid_until: None,
            temporary_until: None,
            registered_time: None,
            version_cause_type: None,
            version_cause_type_value: None,
            status: None,
            status_value: None,
            versionable_status: None,
            versionable_status_value: None,
        }
    }
}

