/*
 * Offentlig Akvakulturregister
 *
 * API for det nye offentlige Akvakulturregisteret
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: akva-hjelp@fiskeridir.no
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// VersionOverview : Oversikt over versjoner.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VersionOverview {
    /// Tidsstempel for når versjonen er gyldig fra.
    #[serde(rename = "validFrom", skip_serializing_if = "Option::is_none")]
    pub valid_from: Option<String>,
    /// Tidsstempel for når versjonen er gyldig til.
    #[serde(rename = "validUntil", skip_serializing_if = "Option::is_none")]
    pub valid_until: Option<String>,
    /// Tidsstempel for når versjonen er midlertidig gyldig til.
    #[serde(rename = "temporaryUntil", skip_serializing_if = "Option::is_none")]
    pub temporary_until: Option<String>,
    /// Årsakstype for versjonen.
    #[serde(rename = "versionCauseType", skip_serializing_if = "Option::is_none")]
    pub version_cause_type: Option<String>,
    /// Årsakstype-verdi.
    #[serde(rename = "versionCauseTypeValue", skip_serializing_if = "Option::is_none")]
    pub version_cause_type_value: Option<String>,
    /// Status.
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    /// Statusverdi.
    #[serde(rename = "statusValue", skip_serializing_if = "Option::is_none")]
    pub status_value: Option<String>,
}

impl VersionOverview {
    /// Oversikt over versjoner.
    pub fn new() -> VersionOverview {
        VersionOverview {
            valid_from: None,
            valid_until: None,
            temporary_until: None,
            version_cause_type: None,
            version_cause_type_value: None,
            status: None,
            status_value: None,
        }
    }
}

